#!/usr/bin/env bash
# -----------------------------------------------------
#
# Script		: anota
# Descrição		: um pequeno gerenciador de notas pessois em modo texto
# Versão		: 0.9.1-beta
# Autor			: Eppur Si Muove
# Contato		: eppur.si.muove.@keemail.me
# Criação		: 29/12/2019
# Modificação	: 24/01/2020
# Licença		: GNU/GPL v3.0
#
# ------------------------------------------------------
#
# Uso:
#
#
# ------------------------------------------------------

# -----------| Carrega Biblioteca principal  |----------- #
# >> CFG_DIR		: diretorio do arquivo de configuração
# >> CFG_ARQ		: nome completo do arquivo de configuração
# >> DB_ARQ			: nome completo do arquivo da base de dados
# >> EDT_FAV		: nome do editor favorito do usuário
# >> NT_DIR			: diretório das notas do usuário
# >> ARRCADERNOS	: lista (array) com o nome de cada caderno do usuário
# >> ARRNOTAS		: lista (array) com o nome de cada nota dentro do caderno selecionado
source $(dirname $0)/anotalib

# -------------| Menu com Lista de Notas |----------------- #
menuNotas(){
	listaNotasPorCaderno $1
	local numNota=$?

	# ----------------->> numNota = 0 : Voltar
	if [[ $numNota -eq 0 ]]; then
		menuCadernos

	# ----------------->> numNota = 1 : Nova Nota	
	elif [[ $numNota -eq 1 ]]; then
		novaNota $1
		[[ $? -ne 0 ]] && echo "Algo saiu errado ao criar a nova nota. Saindo..." && sleep 3 && exit 1
		menuNotas $1

	# ----------------->> numNota = 2 : Remover uma Nota	
	elif [[ $numNota -eq 2 ]]; then
		if [[ ${#ARRNOTAS[@]} -eq 0 ]]; then
			echo "# Sem notas para remover nesse caderno :) "
			sleep 2
			menuNotas $1
		else			
			removeNota $1
			menuNotas $1
		fi

	# ----------------->> numNota maior que itens na array de notas : ERRO!
	elif [[ $(($numNota-3)) -gt ${#ARRNOTAS[@]} ]]; then
		echo "Índices da array de cadernos = ${#ARRNOTAS[@]}."
		echo "Numero escolhido = $numNota"
		echo "Nome, se houver = ${ARRNOTAS[$numNota]}"
		echo "Erro interno!" && sleep 2 && exit 1
	else

	# ----------------->> numNota válido : abre nota com editor preferido
		local nota_arq="$NT_DIR/${ARRCADERNOS[$1]}/${ARRNOTAS[$numNota]}.nta"
		abreNota $nota_arq
		menuNotas $1
	fi
}

# -------------| Menu com Lista de Cadernos |----------------- #
menuCadernos(){
	escolheCaderno
	local numCaderno=$?
	# ----------------->> numCarderno = 0 : Sair
	if [[ $numCaderno -eq 0 ]]; then
		echo "# -----------| :Obrigado por utilizar o ANOTA! Saindo...: |----------- #"
		sleep 2
		exit 0

	# ----------------->> numCaderno = 1 : Novo Caderno	
	elif [[ $numCaderno -eq 1 ]]; then
		novoCaderno
		[[ $? -ne 0 ]] && echo "Algo saiu errado ao criar o novo caderno. Saindo..." && sleep 3 && exit 1
		menuCadernos

	# ------------------>> numCaderno = 2 : Remover um caderno
	elif [[ $numCaderno -eq 2 ]]; then
		if [[ ${#ARRCADERNOS[@]} -eq 0 ]]; then
			echo "# Sem cadernos para remover aqui :) "
			sleep 2
			menuCadernos
		else
			removeCaderno
			menuCadernos
		fi

	# ------------------>> numCaderno maior que itens na array de cadernos: ERRO!
	elif [[ $(($numCaderno-3)) -gt ${#ARRCADERNOS[@]} ]]; then
		echo "Índices da array de cadernos = ${#ARRCADERNOS[@]}."
		echo "Numero escolhido = $numCaderno"
		echo "Nome, se houver = ${ARRCADERNOS[$numCaderno]}"
		echo "Erro interno!" && sleep 2 && exit 1

	# ------------------>> numCaderno válido: retorna número do caderno selecionado
	else
		menuNotas $numCaderno
	fi
}

# -------------| Início do Programa ANOTA! Divirta-se ! |----------------- #

# se necessário, usuário vai escolher um editor favorito
defineEditor $1
[[ $? -ne 0 ]] && echo "Algo saiu errado ao definir o editor. Saindo..." && sleep 2 && exit 1

# se diretório de notas estiver vazio, ele cria a primeira nota dentro do caderno Bem-Vindo
if (estaVazio $NT_DIR); then
	primeiraNota
	[[ $? -ne 0 ]] && echo "Algo saiu errado ao criar a primeira nota. Saindo..." && sleep 2 && exit 1
fi

menuCadernos

